POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "description": "New occupational health care entry",
    "date": "2022-01-11",
    "specialist": "Matti",
    "diagnosisCodes": ["S62.5"],
    "type": "OccupationalHealthcare",
    "employerName": "Seppo",
    "sickLeave": {
      "startDate": "2022-02-22",
      "endDate": "2022-02-23"
    }
}