name: Deployment pipeline

on:
  push:
    branches:
      - main
    paths:
      - part11/full-stack-open-pokedex/**
      - .github/workflows/**
  pull_request:
    branches: [main]
    types: [opened, synchronize]

defaults:
  run:
    working-directory: ./part11/full-stack-open-pokedex/

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message), '; ') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
          working-directory: ./part11/full-stack-open-pokedex/
      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: github.event_name == 'push'
      - run: flyctl deploy --remote-only
        if: github.event_name == 'push'

  tag_release:
    if: |
      github.event_name == 'push'
        && ${{ !contains(env.COMMIT_MESSAGES, '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          # Remove DRY_RUN when in proper use
          DRY_RUN: true
